config/routes.rb
Terranullrecordings::Application.routes.draw do
  devise_for :admins
  resources :news_items, only: :index, path: '/news'
  resources :podcasts, only: :index
  resources :releases, only: [:index, :show]

  namespace :admin do
    resources :news_items
    resources :podcasts
    resources :releases

    root to: 'overview#index'
  end

  root to: 'homepage#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  include Sluggify

  has_slug :title

  default_scope -> { order 'created_at DESC' }

  def to_hash
    {
      id: slug,
      title: title,
      date_text: date_text,
      content: content,
      featured_image: featured_image
    }
  end
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  include Sluggify

  has_slug :title

  default_scope -> { order 'created_at DESC' }

  def to_hash
    {
      id: slug,
      title: title,
      artist: artist,
      tracklist: tracklist,
      embed_code: embed_code,
      large_cover_src: large_cover_src,
      thumbnail_src: thumbnail_src
    }
  end
end

app/models/release.rb
class Release < ActiveRecord::Base
  include Sluggify

  has_slug :title

  default_scope -> { order 'created_at DESC' }

  def released?
    beatport_link || juno_link || itunes_link || bandcamp_link
  end

  def to_hash
    {
      id: slug,
      title: title,
      artist: artist,
      description: description,
      catalog_number: catalog_number,
      release_date: release_date,
      cover_src: cover_src,
      cover_thumbnail_src: cover_thumbnail_src,
      large_cover_src: large_cover_src,
      juno_link: juno_link,
      itunes_link: itunes_link,
      beatport_link: beatport_link,
      bandcamp_link: bandcamp_link,
      released: released?,
      art_series: art_series
    }
  end
end

app/models/slug.rb
class Slug < Struct.new(:string)
  def self.create(string)
    new(string).slug
  end

  def slug
    string.parameterize
  end
end

app/controllers/admin/news_items_controller.rb
class Admin::NewsItemsController < AdminController
  expose(:news_item, attributes: :news_item_params)
  expose(:news_items)

  def create
    redirect_to news_items_path if news_item.save
  end

  def destroy
    redirect_to action: :index if news_item.destroy
  end

  def update
    redirect_to news_items_path if news_item.save
  end

  private
  def news_item_params
    params.require(:news_item).permit(
      :title,
      :date_text,
      :featured_image,
      :content
    )
  end
end

app/controllers/admin/overview_controller.rb
class Admin::OverviewController < AdminController
end

app/controllers/admin/podcasts_controller.rb
class Admin::PodcastsController < AdminController
  expose(:podcast, attributes: :podcast_params)
  expose(:podcasts)

  def create
    redirect_to podcasts_path if podcast.save
  end

  def destroy
    redirect_to action: :index if podcast.destroy
  end

  def update
    redirect_to podcasts_path if podcast.save
  end

  private
  def podcast_params
    params.require(:podcast).permit(
      :title,
      :artist,
      :thumbnail_src,
      :large_cover_src,
      :embed_code,
      :tracklist
    )
  end
end

app/controllers/admin/releases_controller.rb
class Admin::ReleasesController < AdminController
  expose(:release, attributes: :release_params)
  expose(:releases)

  def create
    redirect_to release_path(release.slug) if release.save
  end

  def destroy
    redirect_to action: :index if release.destroy
  end

  def update
    redirect_to release_path(release.slug) if release.save
  end

  private
  def release_params
    params.require(:release).permit(
      :title,
      :artist,
      :catalog_number,
      :cover_src,
      :cover_thumbnail_src,
      :large_cover_src,
      :release_date,
      :juno_link,
      :itunes_link,
      :beatport_link,
      :bandcamp_link,
      :description
    )
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_filter :authenticate_admin!

  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  before_filter :redirect_to_bandcamp
  def redirect_to_bandcamp
    redirect_to 'http://terranullrecordings.bandcamp.com'
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  expose(:news_items)
  expose(:news_item) { NewsItem.find_by(slug: params[:id]) }

  def index
    respond_to do |format|
      format.json { render json: { news: news_items.map(&:to_hash) } }
      format.html { redirect_to '/#/news' }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: { news_item: news_item.to_hash } }
      format.html { redirect_to "/#/news/#{news_item.slug}" }
    end
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  expose(:podcasts)

  def index
    respond_to do |format|
      format.json { render json: { podcasts: podcasts.map(&:to_hash) } }
      format.html { redirect_to '/#/podcasts' }
    end
  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  expose(:releases)
  expose(:release) { Release.find_by(slug: params[:id]) }

  def index
    respond_to do |format|
      format.json { render json: { releases: releases.map(&:to_hash) } }
      format.html { redirect_to '/#/releases' }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: { release: release.to_hash } }
      format.html { redirect_to "/#/releases/#{release.slug}" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/news_items/_form.html.haml
= bootstrap_form_for news_item, url: admin_news_item_path(news_item.id) do |f|
  = f.text_field :title
  = f.text_field :date_text
  = f.text_field :featured_image
  = f.text_area :content

  = f.submit

app/views/admin/news_items/edit.html.haml
%h1 Edit News Item

= render 'form', news_item: news_item

= link_to 'Back', admin_news_items_path

app/views/admin/news_items/index.html.haml
- news_items.each do |news_item|
  .news_item
    = news_item.title
    = link_to 'Edit', edit_admin_news_item_path(news_item)
    = link_to 'Delete', admin_news_item_path(news_item), method: 'delete'
= link_to 'Create New', new_admin_news_item_path
= link_to 'Back', admin_root_path

app/views/admin/news_items/new.html.haml
%h1 Create News Item

= render 'form', news_item: news_item

= link_to 'Back', admin_news_items_path

app/views/admin/overview/index.html.haml
.admin_link
  = link_to 'Edit Releases', admin_releases_path

.admin_link
  = link_to 'Edit Podcasts', admin_podcasts_path

.admin_link
  = link_to 'Edit News Items', admin_news_items_path

app/views/admin/podcasts/_form.html.haml
= bootstrap_form_for podcast, url: admin_podcast_path(podcast.id) do |f|
  = f.text_field :title
  = f.text_field :artist
  = f.text_field :thumbnail_src
  = f.text_field :large_cover_src
  = f.text_area :embed_code
  = f.text_area :tracklist

  = f.submit

app/views/admin/podcasts/edit.html.haml
%h1 Edit Podcast

= render 'form', podcast: podcast

= link_to 'Back', admin_podcasts_path

app/views/admin/podcasts/index.html.haml
- podcasts.each do |podcast|
  .podcast
    = podcast.title
    = link_to 'Edit', edit_admin_podcast_path(podcast)
    = link_to 'Delete', admin_podcast_path(podcast), method: 'delete'
= link_to 'Create New', new_admin_podcast_path
= link_to 'Back', admin_root_path

app/views/admin/podcasts/new.html.haml
%h1 Create Podcast

= render 'form', podcast: podcast

= link_to 'Back', admin_podcasts_path

app/views/admin/releases/_form.html.haml
= bootstrap_form_for release, url: admin_release_path(release.id) do |f|
  = f.text_field :title
  = f.text_field :artist
  = f.text_field :catalog_number
  = f.text_field :cover_src
  = f.text_field :cover_thumbnail_src
  = f.text_field :large_cover_src
  = f.text_field :release_date
  = f.text_field :juno_link
  = f.text_field :itunes_link
  = f.text_field :beatport_link
  = f.text_field :bandcamp_link
  = f.text_area :description

  = f.submit

app/views/admin/releases/edit.html.haml
%h1 Edit Release

= render 'form', release: release

= link_to 'Back', admin_releases_path

app/views/admin/releases/index.html.haml
- releases.each do |release|
  .release
    = release.title
    = link_to 'Edit', edit_admin_release_path(release)
    = link_to 'Delete', admin_release_path(release), method: 'delete'
= link_to 'Create New', new_admin_release_path
= link_to 'Back', admin_root_path

app/views/admin/releases/new.html.haml
%h1 New Release

= render 'form', release: release

= link_to 'Back', admin_releases_path

app/views/homepage/index.html.haml
%script{type: 'text/x-handlebars'}
  #main-wrapper
    #header-wrapper
      #header
        #nav-wrapper-left
          %ul.nav.primary-nav.primary-nav-left
            %li
              {{#linkTo 'releases'}}Releases{{/linkTo}}
            %li
              {{#linkTo 'news'}}News{{/linkTo}}
          .clear
        #small-logo
        #nav-wrapper-right
          %ul.nav.primary-nav.primary-nav-right
            %li
              %a{ href: 'http://terranullrecordings.bandcamp.com', target: '_blank' }
                Store
            %li
              {{#linkTo 'podcasts'}}Podcasts{{/linkTo}}
          .clear
        .clear
      .clear
    #main
      #secondary-content
        {{outlet}}
      .clear

    #social-media
      %a{ href: 'http://terranullrecordings.bandcamp.com', target: '_blank' }
        %img{ src: '/assets/icon_0005_Layer-1.png' }
      %a{ href: 'http://www.facebook.com/terranullrecordings', target: '_blank' }
        %img{ src: '/assets/icon_0004_Layer-2.png' }
      %a{ href: 'http://www.twitter.com/terranullrecs', target: '_blank' }
        %img{ src: '/assets/icon_0003_Layer-3.png' }
      %a{ href: 'http://www.soundcloud.com/terranullrecordings', target: '_blank' }
        %img{ src: '/assets/icon_0002_Layer-4.png' }
      %a{ href: 'http://www.mixcloud.com/terranullrecordings', target: '_blank' }
        %img{ src: '/assets/icon_0001_Layer-5.png' }
      %a{ href: 'http://www.youtube.com/channel/UC9Fgz_TEywYWZ43BbI9GnkA', target: '_blank' }
        %img{ src: '/assets/icon_0000_Layer-6.png' }

  #footer-wrapper
    #footer
      &copy; 2016 TERRA NULL RECORDINGS. ALL RIGHTS RESERVED

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Terra Null Recordings
    = stylesheet_link_tag "admin", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true
    = favicon_link_tag asset_path 'terra_null_logo_favicon.ico'
    = csrf_meta_tags
  %body
    #admin-container
      #admin-nav
        - if admin_signed_in?
          = "Logged in as #{current_admin.email}"
          = link_to "Logout", destroy_admin_session_path, method: :delete
      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Terra Null Recordings
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = favicon_link_tag asset_path 'terra_null_logo_favicon.ico'
    = csrf_meta_tags
  %body
    = yield